CREATE TABLE public.store (
s_store_sk int8 NULL,
s_store_id varchar(16) NULL,
s_rec_start_date date NULL,
s_rec_end_date date NULL,
s_closed_date_sk int8 NULL,
s_store_name varchar(50) NULL,
s_number_employees int4 NULL,
s_floor_space int4 NULL,
s_hours varchar(20) NULL,
s_manager varchar(40) NULL,
s_market_id int4 NULL,
s_geography_class varchar(100) NULL,
s_market_desc varchar(100) NULL,
s_market_manager varchar(40) NULL,
s_division_id int4 NULL,
s_division_name varchar(50) NULL,
s_company_id int4 NULL,
s_company_name varchar(50) NULL,
s_street_number varchar(10) NULL,
s_street_name varchar(60) NULL,
s_street_type varchar(15) NULL,
s_suite_number varchar(10) NULL,
s_city varchar(60) NULL,
s_county varchar(30) NULL,
s_state varchar(2) NULL,
s_zip varchar(10) NULL,
s_country varchar(20) NULL,
s_gmt_offset numeric(5, 2) NULL,
s_tax_precentage numeric(5, 2) NULL
);
