CREATE TABLE public.store_sales (
ss_sold_date_sk int8 NULL,
ss_sold_time_sk int8 NULL,
ss_item_sk int8 NULL,
ss_customer_sk int8 NULL,
ss_cdemo_sk int8 NULL,
ss_hdemo_sk int8 NULL,
ss_addr_sk int8 NULL,
ss_store_sk int8 NULL,
ss_promo_sk int8 NULL,
ss_ticket_number int8 NULL,
ss_quantity int4 NULL,
ss_wholesale_cost numeric(7, 2) NULL,
ss_list_price numeric(7, 2) NULL,
ss_sales_price numeric(7, 2) NULL,
ss_ext_discount_amt numeric(7, 2) NULL,
ss_ext_sales_price numeric(7, 2) NULL,
ss_ext_wholesale_cost numeric(7, 2) NULL,
ss_ext_list_price numeric(7, 2) NULL,
ss_ext_tax numeric(7, 2) NULL,
ss_coupon_amt numeric(7, 2) NULL,
ss_net_paid numeric(7, 2) NULL,
ss_net_paid_inc_tax numeric(7, 2) NULL,
ss_net_profit numeric(7, 2) NULL
);
