CREATE TABLE public.web_returns (
wr_returned_date_sk int8 NULL,
wr_returned_time_sk int8 NULL,
wr_item_sk int8 NULL,
wr_refunded_customer_sk int8 NULL,
wr_refunded_cdemo_sk int8 NULL,
wr_refunded_hdemo_sk int8 NULL,
wr_refunded_addr_sk int8 NULL,
wr_returning_customer_sk int8 NULL,
wr_returning_cdemo_sk int8 NULL,
wr_returning_hdemo_sk int8 NULL,
wr_returning_addr_sk int8 NULL,
wr_web_page_sk int8 NULL,
wr_reason_sk int8 NULL,
wr_order_number int8 NULL,
wr_return_quantity int4 NULL,
wr_return_amt numeric(7, 2) NULL,
wr_return_tax numeric(7, 2) NULL,
wr_return_amt_inc_tax numeric(7, 2) NULL,
wr_fee numeric(7, 2) NULL,
wr_return_ship_cost numeric(7, 2) NULL,
wr_refunded_cash numeric(7, 2) NULL,
wr_reversed_charge numeric(7, 2) NULL,
wr_account_credit numeric(7, 2) NULL,
wr_net_loss numeric(7, 2) NULL
);
