CREATE TABLE public.web_site (
web_site_sk int8 NULL,
web_site_id varchar(16) NULL,
web_rec_start_date date NULL,
web_rec_end_date date NULL,
web_name varchar(50) NULL,
web_open_date_sk int8 NULL,
web_close_date_sk int8 NULL,
web_class varchar(50) NULL,
web_manager varchar(40) NULL,
web_mkt_id int4 NULL,
web_mkt_class varchar(50) NULL,
web_mkt_desc varchar(100) NULL,
web_market_manager varchar(40) NULL,
web_company_id int4 NULL,
web_company_name varchar(50) NULL,
web_street_number varchar(10) NULL,
web_street_name varchar(60) NULL,
web_street_type varchar(15) NULL,
web_suite_number varchar(10) NULL,
web_city varchar(60) NULL,
web_county varchar(30) NULL,
web_state varchar(2) NULL,
web_zip varchar(10) NULL,
web_country varchar(20) NULL,
web_gmt_offset numeric(5, 2) NULL,
web_tax_percentage numeric(5, 2) NULL
);
