CREATE TABLE public.web_sales (
ws_sold_date_sk int8 NULL,
ws_sold_time_sk int8 NULL,
ws_ship_date_sk int8 NULL,
ws_item_sk int8 NULL,
ws_bill_customer_sk int8 NULL,
ws_bill_cdemo_sk int8 NULL,
ws_bill_hdemo_sk int8 NULL,
ws_bill_addr_sk int8 NULL,
ws_ship_customer_sk int8 NULL,
ws_ship_cdemo_sk int8 NULL,
ws_ship_hdemo_sk int8 NULL,
ws_ship_addr_sk int8 NULL,
ws_web_page_sk int8 NULL,
ws_web_site_sk int8 NULL,
ws_ship_mode_sk int8 NULL,
ws_warehouse_sk int8 NULL,
ws_promo_sk int8 NULL,
ws_order_number int8 NULL,
ws_quantity int4 NULL,
ws_wholesale_cost numeric(7, 2) NULL,
ws_list_price numeric(7, 2) NULL,
ws_sales_price numeric(7, 2) NULL,
ws_ext_discount_amt numeric(7, 2) NULL,
ws_ext_sales_price numeric(7, 2) NULL,
ws_ext_wholesale_cost numeric(7, 2) NULL,
ws_ext_list_price numeric(7, 2) NULL,
ws_ext_tax numeric(7, 2) NULL,
ws_coupon_amt numeric(7, 2) NULL,
ws_ext_ship_cost numeric(7, 2) NULL,
ws_net_paid numeric(7, 2) NULL,
ws_net_paid_inc_tax numeric(7, 2) NULL,
ws_net_paid_inc_ship numeric(7, 2) NULL,
ws_net_paid_inc_ship_tax numeric(7, 2) NULL,
ws_net_profit numeric(7, 2) NULL
);
